import {fingerprint,identity} from '../src/core/policy.mjs';
import {createThreatLedger} from '../src/combat/threats.mjs';
import {createGearAllocation} from '../src/production/allocation.mjs';
import {createContentGuard} from '../src/world/content.mjs';
import {killQuantile,materialEvent} from '../src/production/probability.mjs';
import {createProduction} from '../src/production/production.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultsFor,envelope,importProfile} from '../editor/lib/contract.mjs';
import {FULL_DESCRIPTOR} from '../src/config/full.mjs';
import {createStrategy} from '../src/world/strategy.mjs';
import {createTeamPlan} from '../src/world/team-plan.mjs';
import {spawnLocations,mapGraph,mapHops,knowledgeFingerprint} from '../src/world/knowledge.mjs';
import {materialSources} from '../src/production/materials.mjs';
import {chooseElixir,createElixirs} from '../src/items/elixirs.mjs';
import {createPriorityScheduler} from '../src/core/priority.mjs';
import {assessServerHop} from '../src/world/servers.mjs';
import {createRecovery} from '../src/core/recovery.mjs';
import {chooseCombatLeader} from '../src/party/account.mjs';
import {createMarket} from '../src/merchant/market.mjs';
import {createEconomicIntelligence,progressionChance} from '../src/production/intelligence.mjs';
function fixture(){const cfg=defaultsFor(FULL_DESCRIPTOR.schema);cfg.party.leader='A';cfg.party.merchant='M';cfg.farming.mode='xp';cfg.farming.targets=['goo'];cfg.characters=['A','B'].map(name=>({...defaultsFor(FULL_DESCRIPTOR.schema.properties.characters.items),name,class:'ranger'}));cfg.characters.push({...defaultsFor(FULL_DESCRIPTOR.schema.properties.characters.items),name:'M',class:'merchant',role:'merchant'});
 const c={name:'A',ctype:'ranger',level:60,hp:4000,max_hp:4000,mp:1000,max_mp:1000,attack:300,frequency:1,speed:40,map:'main',in:'main',x:0,y:0,items:Array(42).fill(null),slots:{}},G={maps:{main:{monsters:[{type:'goo',count:1,boundary:[-10,-10,10,10]},{type:'bee',count:3,boundary:[100,100,120,120]},{type:'prat',count:2,boundary:[200,200,300,300]}],doors:[[0,0,1,1,'other',0]]},other:{monsters:[]},hidden:{instance:true,monsters:[{type:'bee',boundary:[0,0,10,10]}]}},monsters:{goo:{hp:100,attack:5,frequency:.4,xp:10,respawn:1},bee:{hp:300,attack:16,frequency:.5,xp:100,respawn:1},prat:{hp:9200,attack:320,frequency:1.6,xp:100000,respawn:1}},items:{},skills:{heal:{class:['priest'],level:1},energize:{class:['mage'],level:1}},drops:{monsters:{bee:[[.1,'mat']]}}};
 const data=new Map(),peers={},events=[],calls=[];const bot={cfg,me:cfg.characters[0],running:true,session:'a-session',leader:'A',farmers:['A','B'],teamNames:['A','B','M'],journal:null,inventoryBlocked:false,p:{c,G,root:{},parent:{},entities:{},realm:()=> 'EUII',read:k=>data.get(k),write:(k,v)=>{data.set(k,structuredClone(v));return true;},has:()=>true,call:(name,...args)=>{calls.push([name,...args]);return name==='item_grade'?0:name==='item_properties'?{attack:(args[0]?.level??0)*20+10,dex:5}:true;}},transport:{peers:new Map(),fresh:n=>peers[n]},movement:{order:null,stop(){this.order=null;},go(d,owner){this.order={dest:d,owner};},farmLocation(){}},monsters:()=>Object.values(bot.p.entities).filter(e=>e.type==='monster'),event:(type,details)=>events.push({type,details}),report(){},count:name=>c.items.reduce((n,i)=>n+(i?.name===name?(i.q??1):0),0),consumable:()=>true,production:{farmTargets:()=>null,progress:()=>[],reservedQuantity:()=>0},economy:{explicit:()=>null,safe:i=>i&&!i.l&&!i.b,value:()=>10,perform:(kind,job)=>{if(job.guard&&!job.guard())return false;job.call();return true;}},checkpoint:{durable:true},logistics:{reserved:false},exec:{pending:new Map()},endValue(){this.journal=null;}};peers.B={name:'B',running:true,realm:'EUII',map:'main',in:'main',x:0,y:0,hp:4000,max_hp:4000,class:'ranger',stats:{attack:300,frequency:1}};bot.strategy=createStrategy(bot);bot.teamPlan=createTeamPlan(bot);return {bot,c,G,cfg,data,peers,events,calls};}
test('shared planner chooses safe XP spawn beyond configured Goo and excludes instances',()=>{const {bot}=fixture();bot.teamPlan.tick();assert.equal(bot.teamPlan.target(),'bee');assert.equal(bot.strategy.targets()[0],'bee');assert.equal(bot.teamPlan.status().ranking.some(x=>x.map==='hidden'),false);assert.equal(bot.teamPlan.status().ranking.some(x=>x.target==='prat'),false);});
test('automatic candidates can be disabled and character whitelist remains authoritative',()=>{const {bot,cfg}=fixture();cfg.farming.autoTargets=false;bot.teamPlan.tick();assert.equal(bot.teamPlan.target(),'goo');const b=fixture();b.bot.me.farmTargets=['goo'];b.bot.teamPlan.tick();assert.equal(b.bot.teamPlan.target(),'goo');});
test('follower adopts same objective and never invents independent fallback when leader disappears',()=>{const a=fixture();a.bot.teamPlan.tick();const b=fixture();b.bot.me=b.cfg.characters[1];b.c.name='B';b.bot.session='b-session';b.peers.A={...a.c,name:'A',running:true,realm:'EUII',farmPlan:a.bot.teamPlan.heartbeat()};b.bot.teamPlan=createTeamPlan(b.bot);b.bot.teamPlan.tick();assert.equal(b.bot.teamPlan.heartbeat().id,a.bot.teamPlan.heartbeat().id);b.peers.A.running=false;b.bot.teamPlan.tick();assert.equal(b.bot.teamPlan.target(),null);assert.deepEqual(b.bot.strategy.targets(),[]);});
test('material request outranks XP and validates source definition and expiry',()=>{const {bot,peers,G}=fixture();peers.M={running:true,materials:[{monster:'goo',item:'mat',quantity:5,objective:'job-1',expires:Date.now()+30000,sourceFingerprint:knowledgeFingerprint([G.monsters.goo,G.drops.monsters.goo])}]};bot.teamPlan.tick();assert.equal(bot.teamPlan.target(),'goo');assert.equal(bot.teamPlan.materialActive(),true);peers.M.materials[0].remaining=0;assert.equal(bot.teamPlan.wantsCombat(),false);G.monsters.goo.hp=200;assert.equal(bot.teamPlan.target(),null);});
test('group travel can assess known remote peers while actual attack remains locally gated',()=>{const {bot,peers}=fixture();peers.B.map='other';assert.equal(bot.strategy.safeTarget('bee',undefined,true,true),true);bot.teamPlan.tick();assert.equal(bot.teamPlan.target(),'bee');});
test('spawn changes invalidate propagated plan and graph retains directed connections',()=>{const {bot,G}=fixture();bot.teamPlan.tick();G.monsters.bee.attack=50000;assert.equal(bot.teamPlan.target(),null);const graph=mapGraph(G);assert.equal(mapHops(graph,'main','other'),1);assert.equal(mapHops(graph,'other','main'),Infinity);});
test('planner assigns healer and support from fresh capabilities',()=>{const {bot,peers}=fixture();peers.B.class='priest';peers.B.skills=['heal'];bot.teamPlan.tick();assert.equal(bot.teamPlan.roles().heal,'B');assert.equal(bot.teamPlan.roles().energize,null);});
test('spawn pressure observations survive restart with bounded site history',()=>{const {bot,data}=fixture();bot.teamPlan.tick();bot.teamPlan.tick();assert.ok(data.get('albot:teamplan:A:areas'));const restored=createTeamPlan(bot);assert.ok(restored.status().areas>0);});
test('material estimate distinguishes expectation/P90 and excludes inactive or too-short events',()=>{const {G}=fixture();const rows=materialSources(G,'mat',3,['bee'],20,()=>({value:100,source:'observed-team'}));assert.ok(rows[0].p90Hours>rows[0].estimatedHours);G.monsters.bee.event='beetime';assert.deepEqual(materialSources(G,'mat',3,['bee'],20,undefined,{state:{}}),[]);const active=materialSources(G,'mat',3,['bee'],20,()=>({value:100,source:'observed-team'}),{state:{beetime:{live:true,expires:Date.now()+86400000}}});assert.equal(active[0].sourceKind,'event-drop');});
test('elixir selection follows class stat and utility instead of any consumable',()=>{const {G}=fixture();G.items={dex:{type:'elixir',dex:10,duration:1,g:10},str:{type:'elixir',str:20,duration:1,g:10},bad:{type:'pot',dex:100,duration:1,g:1}};assert.equal(chooseElixir(G,'ranger').name,'dex');assert.equal(chooseElixir(G,'warrior').name,'str');});
test('elixir equip respects protected items, renewal threshold and repeatable supply cycles',()=>{const {bot,c,G,calls}=fixture();G.items.dex={type:'elixir',dex:10,duration:1,g:10};const elixirs=createElixirs(bot);const first=elixirs.request();c.slots.elixir={name:'dex',expires:new Date(Date.now()+3600000).toISOString()};assert.equal(elixirs.request(),null);c.slots.elixir=null;assert.ok(elixirs.request().cycle>first.cycle);c.items[0]={name:'dex',l:true};assert.equal(elixirs.tick(),false);assert.equal(calls.length,0);});
test('explicit keep stops automated elixir acquisition',()=>{const {bot,G}=fixture();G.items.dex={type:'elixir',dex:10,duration:1,g:10};bot.economy.explicit=()=>({action:'keep'});assert.equal(createElixirs(bot).request(),null);});
test('global task scheduler gives emergency exclusive ownership ahead of normal/background',()=>{const {bot}=fixture(),calls=[];const q=createPriorityScheduler(bot);q.run([{id:'trade',kind:'normal',priority:999,run:()=>calls.push('trade')},{id:'heal',kind:'emergency',exclusive:true,run:()=>calls.push('heal')}]);assert.deepEqual(calls,['heal']);assert.equal(q.status().waiting,2);q.close();assert.equal(q.status().waiting,0);});
test('server registry rejects stale/offline/unknown/high-risk and exhausted hop windows',()=>{const now=100000,s={online:true,mode:'NORMAL',at:now};const policy={pvp:false,cooldown:1000};assert.equal(assessServerHop(s,[],now,policy).allowed,true);for(const patch of [{at:0},{online:false},{mode:'UNBEKANNT'},{mode:'HARDCORE'},{mode:'PVP'}])assert.equal(assessServerHop({...s,...patch},[],now,policy).allowed,false);assert.equal(assessServerHop(s,[now-2000,now-3000,now-4000],now,policy).allowed,false);});
test('recovery confirms exact purchase evidence but never infers sent transfer receipt',()=>{const {bot,c}=fixture();c.items[0]={name:'mat',q:2};c.gold=80;bot.journal={kind:'buy',at:1,item:'mat',variant:identity({name:'mat',q:2}),before:0,quantity:2,cost:20,evidence:{gold:100,realm:'EUII',inventory:Array(42).fill(null)}};bot.inventoryBlocked=true;assert.equal(createRecovery(bot).reconcile(),true);assert.equal(bot.inventoryBlocked,false);bot.journal={kind:'send',at:2,item:'mat',evidence:{gold:100,realm:'EUII'}};assert.equal(createRecovery(bot).reconcile(),false);assert.ok(bot.journal);});
test('bank authority refuses a different announced owner and non-merchant',()=>{const {bot}=fixture();const r=createRecovery(bot);assert.equal(r.authorize('bank.store'),false);bot.me.name='M';bot.transport.peers.set('Other',{name:'Other',received:Date.now(),running:true,bankOwner:{owner:'Other'}});assert.equal(r.authorize('bank.store'),false);});
test('default leader election uses current living combat capabilities, never offline candidate',()=>{assert.equal(chooseCombatLeader([{name:'A',running:true,hp:4000,max_hp:4000,class:'warrior',stats:{attack:300,armor:200}},{name:'B',running:false,hp:9999,max_hp:9999,class:'warrior',stats:{attack:90000}}]),'A');});
test('market quote separates bids and asks and requires independent providers',()=>{const {bot,cfg}=fixture();cfg.merchant.marketMinSamples=3;bot.p.entities={};for(let i=0;i<3;i++)bot.p.entities['P'+i]={name:'P'+i,slots:{trade1:{name:'mat',price:100+i*10,q:2},trade2:{name:'mat',price:1000+i*10,b:true,q:1}}};const market=createMarket(bot);assert.equal(market.quote({name:'mat'}),110);const analysis=market.analysis({name:'mat'});assert.equal(analysis.ask,100);assert.equal(analysis.bid,1020);assert.equal(analysis.providers,3);});
test('automatic disposition preserves protected, cash, gear and production reservations',()=>{const {bot,G}=fixture();bot.me.role='merchant';G.items.mat={type:'material',g:20};G.items.cash={type:'material',cash:1};const intel=createEconomicIntelligence(bot);assert.equal(intel.disposition({name:'mat',l:true}),null);assert.equal(intel.disposition({name:'cash'}),null);bot.production.reservedQuantity=()=>1;assert.equal(intel.disposition({name:'mat'}),null);});
test('economic gear chooses available alternative and bounded target rather than fixed current item',()=>{const {bot,c,G,cfg}=fixture();G.classes={ranger:{mainhand:{bow:{}},doublehand:{},offhand:{}}};G.items.bow={type:'weapon',wtype:'bow',g:10,upgrade:{},igrade:0};G.items.scroll0={g:10};cfg.production.autoGear=cfg.production.gear=true;cfg.production.autoGearItems=['bow'];cfg.production.autoGearBudget=1000;cfg.production.minChance=.9;c.slots.mainhand={name:'old',level:0};bot.gear={snapshot:()=>({class:'ranger',level:60,slots:c.slots}),profile:()=>null};const targets=createEconomicIntelligence(bot).targets();assert.ok(targets.length>0);assert.equal(targets[0].item,'bow');assert.ok(targets[0].level<=cfg.production.autoGearMaxLevel);assert.equal(progressionChance(G,'bow',0,'upgrade')>0,true);});
test('full/v1 profile migration adds optional autonomy defaults and preserves explicit limits',()=>{const {cfg}=fixture();delete cfg.farming.autoTargets;cfg.production.autoGearBudget=123;const migrated=importProfile(FULL_DESCRIPTOR,envelope(FULL_DESCRIPTOR,cfg));assert.equal(migrated.farming.autoTargets,true);assert.equal(migrated.production.autoGearBudget,123);});

test('material P50/P90 uses Bernoulli quantiles and seasonal state end aliases',()=>{assert.equal(killQuantile(.1,1,.5),7);assert.equal(killQuantile(.1,1,.9),22);assert.equal(killQuantile(1,3,.9),3);const G={monsters:{w:{}},events:{winter:{monster:'w'}}};assert.equal(materialEvent(G,'w',{}).active,false);assert.equal(materialEvent(G,'w',{winter:{live:true,end:Math.floor(Date.now()/1000)-1}}).active,false);assert.equal(materialEvent(G,'w',{winter:{live:true,end:new Date(Date.now()+60000).toISOString()}}).active,true);});
test('physical gear reservation pins slot, realm and recipient session through settlement',()=>{const {bot,c,peers,data}=fixture();c.items[0]={name:'bow',level:1};bot.gear={goals:()=>[{recipient:'B',item:'bow',level:1,gearSlot:'mainhand'}]};peers.B.session='b1';peers.B.gear={slots:{mainhand:null}};const a=createGearAllocation(bot),j={id:'a1',to:'B',session:'b1',gear:{slot:'mainhand',expected:fingerprint(null)},gearAck:true,slot:0,item:{name:'bow',level:1},fingerprint:JSON.stringify(c.items[0]),quantity:1};j.fingerprint=fingerprint(c.items[0]);delete peers.B.gear;assert.equal(a.offer(j.item,'B'),false);peers.B.gear={slots:{mainhand:null}};assert.equal(a.reserve(j),true);assert.equal(a.guard(j),true);peers.B.session='b2';assert.equal(a.guard(j),false);peers.B.session='b1';c.items[0].level=2;assert.equal(a.guard(j),false);assert.equal(a.settle(j,'unknown'),true);assert.equal(createGearAllocation(bot).status()[0].state,'unresolved');assert.equal(data.size>0,true);});
test('observed threat ownership rejects contested and immune opponents without claiming unhit monsters',()=>{const {bot}=fixture();bot.p.entities.g={id:'g',type:'monster',mtype:'goo',map:'main',in:'main',hp:100,max_hp:100};bot.entity=id=>bot.p.entities[id];bot.teamPlan.lostKill=()=>{};const t=createThreatLedger(bot);t.sample();assert.equal(t.inspect(bot.p.entities.g).ownership,'unclaimed');t.hit({target:'g',actor:'A',damage:1});assert.equal(t.inspect(bot.p.entities.g).ownership,'team-observed');t.hit({target:'g',actor:'Stranger',damage:1});assert.equal(t.permitted(bot.p.entities.g),false);bot.p.entities.g.immune=true;t.sample();assert.equal(t.permitted(bot.p.entities.g),false);t.close();assert.equal(t.status().entries,0);});
test('semantic drift quarantines changed definition until stable, including persisted reload',()=>{const {bot}=fixture(),realNow=Date.now;let now=realNow();Date.now=()=>now;try{const g=createContentGuard(bot);assert.equal(g.approve('farm:bee',{hp:1}),true);g.flush();assert.equal(g.approve('farm:bee',{hp:2}),false);assert.equal(g.status().length,1);now+=31000;g.flush();const reload=createContentGuard(bot);assert.equal(reload.approve('farm:bee',{hp:3}),false);now+=11000;assert.equal(reload.approve('farm:bee',{hp:3}),true);assert.equal(reload.status().length,0);}finally{Date.now=realNow;}});
test('merchant advertises material intent continuously across planning and reload without dispatch',()=>{const {bot,c,cfg,G,data}=fixture();bot.me=cfg.characters[2];bot.me.name='M';c.name='M';c.ctype='merchant';cfg.production.enabled=cfg.production.autonomy=true;cfg.production.acquireBy=['farm'];cfg.production.goals=[{name:'Material',enabled:true,item:'mat',level:0,quantity:2,recipient:'',budget:100,priority:1}];G.items.mat={g:100,type:'material'};bot.bank={stock:()=>0,packs:()=>[],observed:true};bot.market={quote:()=>null};bot.economy.npcFor=()=>null;bot.economy.remaining=()=>true;bot.economy.destination=()=>null;bot.economy.note=()=>{};bot.gear={goals:()=>[]};bot.production=createProduction(bot);bot.production.planGoals();const first=bot.production.materials();assert.equal(first[0]?.item,'mat');assert.ok(first[0].objective);bot.production.planGoals();assert.equal(bot.production.materials()[0].objective,first[0].objective);assert.ok(data.get('albot:production:M:intent'));bot.production=createProduction(bot);bot.production.planGoals();assert.equal(bot.production.materials()[0].objective,first[0].objective);cfg.production.goals=[];bot.production.planGoals();assert.equal(bot.production.materials().length,0);assert.equal(data.get('albot:production:M:intent'),null);});

test('automatic ordinary loot handoff uses shared disposition while explicit and reserved stock stay untouched',()=>{const {bot,c,cfg,G}=fixture();cfg.production.autoDisposition=true;cfg.merchant.pickup=true;G.items.scrap={g:10,type:'material'};c.items[0]={name:'scrap',q:5};const i=createEconomicIntelligence(bot);assert.equal(i.disposition(c.items[0]).action,'send');assert.equal(i.rules()[0].recipient,'M');bot.economy.explicit=()=>({action:'keep'});assert.equal(i.rules().length,0);bot.economy.explicit=()=>null;bot.production.reservedQuantity=()=>5;assert.equal(i.disposition(c.items[0]),null);});
test('market minimum provider gate cannot be bypassed by visible listing price choice',()=>{const {bot,c,G,cfg,calls}=fixture();cfg.merchant.marketHistory=false;cfg.merchant.marketMinSamples=3;G.items.mat={g:10};c.items[0]={name:'mat',q:5};c.stand=true;c.slots={};bot.economy.spare=()=>5;bot.economy.count=()=>5;bot.p.entities={P:{name:'P',slots:{trade1:{name:'mat',price:100}}}};const r={priceSource:'market',minPrice:1,maxPrice:1000,slot:'trade1'};assert.equal(createMarket(bot).listing(0,r),false);assert.equal(calls.some(x=>x[0]==='trade'),false);});
test('server freshness must have a finite timestamp and never assumes missing online flag',()=>{assert.equal(assessServerHop({mode:'NORMAL',online:true},[],Date.now(),{cooldown:1000}).allowed,false);assert.equal(assessServerHop({mode:'NORMAL',at:Date.now()},[],Date.now(),{cooldown:1000}).allowed,false);});

test('gold ranking uses actual G.monster_gold and gold distribution even when item drop table has no gold',()=>{const {bot,G,cfg}=fixture();cfg.farming.mode='gold';G.monster_gold={goo:10000,bee:1};G.drops.gold={base:.64,random:.8};bot.teamPlan.tick();assert.equal(bot.teamPlan.target(),'goo');assert.ok(bot.teamPlan.status().ranking[0].goldPerHour>0);});

test('economic disposition processes profitable known exchange surplus within loss and probability bounds',()=>{const {bot,c,G,cfg}=fixture();bot.me=cfg.characters[2];cfg.production.autoDisposition=cfg.production.enabled=cfg.production.exchange=true;cfg.production.lossBudget=100;cfg.production.minChance=.9;G.items.token={type:'gem',g:1,e:2};G.items.reward={type:'material',g:20};G.drops.token=[[1,'reward']];c.items[0]={name:'token',q:2};bot.economy.value=i=>G.items[i.name]?.g??0;const intel=createEconomicIntelligence(bot);assert.equal(intel.disposition(c.items[0]).action,'exchange');cfg.production.lossBudget=1;assert.notEqual(intel.disposition(c.items[0])?.action,'exchange');G.drops.token=[[.1,'reward']];cfg.production.lossBudget=100;assert.notEqual(intel.disposition(c.items[0])?.action,'exchange');});

// Regression boundaries from the 0.7.0 parity audit.
test('same plan ID refreshes follower expiry and changed role without stopping movement',()=>{const a=fixture();a.bot.teamPlan.tick();const b=fixture();b.bot.me=b.cfg.characters[1];b.c.name='B';b.peers.A={running:true,realm:'EUII',roles:{heal:'Priest1'},farmPlan:a.bot.teamPlan.heartbeat()};b.bot.teamPlan=createTeamPlan(b.bot);b.bot.teamPlan.tick();const old=b.bot.teamPlan.heartbeat().expires;b.bot.movement.order={owner:'follow'};b.peers.A.farmPlan={...b.peers.A.farmPlan,expires:old+10000};b.peers.A.roles={heal:'Priest2'};b.bot.teamPlan.tick();assert.equal(b.bot.teamPlan.heartbeat().expires,old+10000);assert.equal(b.bot.teamPlan.roles().heal,'Priest2');assert.equal(b.bot.movement.order.owner,'follow');});
test('personal material quota prevents new pulls while aggregate request is incomplete',()=>{const {bot,peers}=fixture();peers.M={running:true,materials:[{monster:'goo',item:'mat',quantity:10,remaining:5,objective:'quota',quotas:[{name:'A',quantity:3}],expires:Date.now()+30000}]};bot.production.progress=()=>[{objective:'quota',quantity:3}];bot.teamPlan.tick();assert.equal(bot.teamPlan.wantsCombat(),false);bot.production.progress=()=>[{objective:'quota',quantity:2}];assert.equal(bot.teamPlan.wantsCombat(),true);});
test('gear receiver rejects stale slot and explicit keep before accepting delivery promise',()=>{const {bot,c,G}=fixture();c.slots.mainhand={name:'bow',level:0};G.items.bow={type:'weapon',wtype:'bow',upgrade:true};G.classes={ranger:{mainhand:{bow:1}}};bot.gear={snapshot:()=>({class:'ranger',level:60,slots:{mainhand:{...c.slots.mainhand,l:false,b:false}}})};const a=createGearAllocation(bot),item={name:'bow',level:2},proposal={slot:'mainhand',expected:fingerprint(bot.gear.snapshot().slots.mainhand),expires:Date.now()+10000};assert.equal(a.accept('g1','M','session',item,proposal),true);assert.equal(a.rules()[0].slot,'mainhand');c.slots.mainhand.level=1;assert.equal(a.equipGuard(item,'mainhand'),false);assert.equal(a.accept('g2','M','session',item,proposal),false);c.slots.mainhand.level=0;bot.economy.explicit=()=>({action:'keep'});assert.equal(a.accept('g3','M','session',item,proposal),false);});
test('compound economics accumulates compatible triples and honours future gear protection',()=>{const {bot,c,G,cfg}=fixture();bot.me.role='merchant';cfg.production.autoGear=false;cfg.production.autoDisposition=cfg.production.enabled=cfg.production.compound=true;cfg.production.minChance=.9;cfg.production.autoGearMaxLevel=1;G.items.ring={compound:true,type:'ring',grades:[10,20]};G.items.cscroll0={g:1};bot.economy.value=i=>i.level===1?100:10;const i={name:'ring',level:0};c.items[0]=i;const intel=createEconomicIntelligence(bot);assert.equal(intel.disposition(i).action,'bank');c.items[1]={...i};c.items[2]={...i};assert.equal(intel.disposition(i).action,'compound');i.l=true;assert.equal(intel.disposition(i),null);});

test('gear source at a lower owned level is requested before buying replacement bases',()=>{const {bot,c,cfg,G,peers}=fixture();bot.me=cfg.characters[2];c.name='M';c.ctype='merchant';cfg.production.enabled=cfg.production.autonomy=true;G.items.bow={type:'weapon',upgrade:{},g:100};peers.B.stock=[{name:'bow',level:2}];bot.gear={goals:()=>[{name:'Gear B',enabled:true,item:'bow',level:3,sourceLevel:2,sourceOwner:'B',quantity:1,recipient:'B',character:'B',gearSlot:'mainhand',budget:100,priority:1}]};bot.bank={stock:()=>0,packs:()=>[],observed:true};bot.economy.note=()=>{};bot.economy.npcFor=()=>({map:'main',x:0,y:0});bot.economy.remaining=()=>true;bot.production=createProduction(bot);bot.production.planGoals();assert.equal(bot.production.activeGoal,null);assert.equal(bot.production.tick(),false);assert.ok(bot.production.effectiveRules().some(r=>r.item==='bow'&&r.minLevel===2&&r.action==='keep'));});

test('production reuses bounded decision-frame goals and rules but invalidates after settlement',()=>{const {bot}=fixture();let calls=0;bot.cfg.production.enabled=bot.cfg.production.autonomy=true;bot.decisionEpoch=1;bot.intelligence={profitGoals(){calls++;return [];},rules:()=>[]};bot.gear={goals:()=>[]};bot.production=createProduction(bot);for(let n=0;n<100;n++){bot.production.reservedQuantity({name:'mat',level:0});bot.production.effectiveRules();}assert.equal(calls,1);bot.production.invalidate();bot.production.effectiveRules();assert.equal(calls,2);bot.decisionEpoch++;bot.production.effectiveRules();assert.equal(calls,3);});


test('upgrade scrolls remain working supplies under automatic disposition',()=>{const {bot,c,G,cfg}=fixture();bot.me=cfg.characters.find(x=>x.role==='merchant');cfg.production.autoDisposition=true;G.items.scroll0={type:'uscroll',g:1000};c.items[0]={name:'scroll0',q:35};const intel=createEconomicIntelligence(bot);assert.equal(intel.disposition(c.items[0]),null);});
