import test from 'node:test';
import assert from 'node:assert/strict';
import {assessCombat} from '../src/world/risk.mjs';
import {createStrategy} from '../src/world/strategy.mjs';
import {createFarmer} from '../src/combat/farmer.mjs';
import {createMerchant} from '../src/merchant/controller.mjs';
import {FULL_DESCRIPTOR} from '../src/config/full.mjs';
import {defaultsFor} from '../editor/lib/contract.mjs';
function fixture(){const cfg=defaultsFor(FULL_DESCRIPTOR.schema);cfg.farming.loot=false;cfg.farming.targets=['goo','bee'];cfg.party.enabled=false;cfg.party.merchant='M';
 const c={name:'A',hp:4182,max_hp:4182,mp:1065,max_mp:1065,attack:363,frequency:.955,map:'main',in:'main',x:0,y:0,items:[]},data=new Map(),events=[],moves=[];
 const G={maps:{main:{},level1:{monsters:[{type:'prat',boundary:[0,0,200,200]}]}},monsters:{goo:{hp:100,attack:5,frequency:.4},bee:{hp:300,attack:16,frequency:.5},prat:{hp:9200,attack:320,frequency:1.6,armor:160,aggro:1}},items:{},skills:{}};
 const bot={cfg,me:{name:'A',role:'farmer',farmTargets:[]},running:true,leader:'A',farmers:['A'],p:{c,G,root:{},parent:{},read:k=>data.get(k),write:(k,v)=>{data.set(k,structuredClone(v));return true;},realm:()=> 'EUII',call:(n)=>n==='can_move_to',has:()=>true},transport:{fresh:()=>null},monsters:()=>[],allies:()=>[c],production:{farmTargets:()=>null},logistics:{reserved:false},exec:{run:()=>false},movement:{order:null,stop(){this.order=null;},local(x,y,owner){moves.push(owner);this.order={owner};},go(){}},skills:{rotation(){}},free:()=>42,event:(name,details)=>events.push({name,details}),pause(){this.running=false;}};bot.strategy=createStrategy(bot);return {bot,c,cfg,G,data,events,moves};}
test('observed ranger team rejects Prat DPS/exposure but permits Bee and Goo',()=>{const {c,G}=fixture();const team=[c,{...c,hp:4422,max_hp:4422},{...c,attack:324,frequency:.944,hp:3884,max_hp:3884}];assert.equal(assessCombat(G.monsters.prat,team,'balanced',3).safe,false);assert.equal(assessCombat(G.monsters.bee,[c],'balanced',3).safe,true);assert.equal(assessCombat(G.monsters.goo,[c],'conservative',3).safe,true);assert.equal(assessCombat(G.monsters.bee,[{...c,frequency:undefined}]).safe,false);});
test('death target cooldown survives restart and emits one failure instead of per-tick writes',()=>{const {bot,data,events}=fixture();bot.strategy.failActivity('Tod','bee');bot.strategy.failActivity('Tod','bee');assert.equal(events.filter(e=>e.name==='strategy.failedTarget').length,1);assert.ok(data.get('albot:risk:A').bee>Date.now());bot.strategy=createStrategy(bot);assert.deepEqual(bot.strategy.targets(),['goo']);});
test('waiting for missing group under fire retreats even above rest threshold',()=>{const {bot,c,cfg,moves}=fixture();cfg.party.enabled=cfg.party.waitForTeam=true;bot.farmers=['A','B'];bot.monsters=()=>[{mtype:'goo',target:'A',x:1,y:0,map:'main',hp:100}];createFarmer(bot).tick();assert.deepEqual(moves,['kite']);assert.equal(bot.recovering,true);assert.equal(bot.target,null);});
test('merchant retreats from own aggro and recovery blocks economy scheduling',()=>{const {bot,moves}=fixture();bot.me.role='merchant';bot.monsters=()=>[{mtype:'goo',target:'A',x:1,y:0,hp:100}];createFarmer(bot).tick();assert.deepEqual(moves,['kite']);assert.equal(bot.recovering,true);bot.bank={get pending(){assert.fail('Recovery must guard even bank scheduling');}};createMerchant(bot).tick();});
test('merchant preserves existing acquisition waypoint instead of reranking alternating purchases',()=>{const {bot,c,cfg}=fixture();bot.me.role='merchant';bot.bank={pending:false};bot.exec.busy=()=>false;bot.production.planGoals=()=>{};bot.logistics.travel=()=>{};bot.movement.order={owner:'economy',dest:{map:'main',x:10,y:10}};bot.economy={safe:()=>assert.fail('Travel must finish before jobs rerank')};cfg.merchant.mluck=false;createMerchant(bot).tick();assert.equal(bot.movement.order.owner,'economy');assert.match(bot.reason,/Unterwegs/);});
test('merchant refuses threatened peer and dangerous Prat spawn destination',()=>{const {bot}=fixture();assert.equal(bot.strategy.canVisit({map:'main',x:10,y:0,hp:4000,max_hp:4000,threats:1}),false);assert.equal(bot.strategy.canVisit({map:'level1',x:100,y:100,hp:4000,max_hp:4000,threats:0}),false);assert.equal(bot.strategy.canVisit({map:'main',x:10,y:0,hp:4000,max_hp:4000,threats:0}),true);});
test('unsafe Monsterhunt never selects Prat and normal farming remains available',()=>{const {bot,c,cfg}=fixture();cfg.world.quests=cfg.world.questTargets=true;c.s={monsterhunt:{id:'prat',c:10}};bot.movement.farmLocation=()=>assert.fail('Unsafe quest must not create route');bot.strategy.plan();assert.equal(bot.strategy.status().activity,null);assert.deepEqual(new Set(bot.strategy.targets()),new Set(['goo','bee']));});

test('death in ordinary farming also quarantines the last combat target',()=>{const {bot,c}=fixture();bot.target={mtype:'bee'};c.rip=true;createFarmer(bot).tick();assert.equal(bot.strategy.safeTarget('bee'),false);assert.equal(bot.recovering,true);});

test('safe remote Bee activity does not require merchant to count as combat member',()=>{const {bot,c,G}=fixture();c.name='M';G.maps.remote={};assert.equal(bot.strategy.canVisit({map:'remote',x:100,y:100,hp:4000,max_hp:4000,threats:0,activity:{target:'bee'}}),true);assert.equal(bot.strategy.canVisit({map:'remote',x:100,y:100,hp:4000,max_hp:4000,threats:0,activity:{target:'prat'}}),false);});

test('unsafe observed farm target triggers bounded replanning instead of idle at its spawn',()=>{const {bot,c}=fixture();bot.teamPlan={target:()=> 'bee',failed(){},travel:()=>false};bot.monsters=()=>[{id:'elite',type:'monster',mtype:'bee',hp:200000,max_hp:200000,attack:1000,frequency:2,map:'main',x:1,y:0}];createFarmer(bot).tick();assert.equal(bot.strategy.safeTarget('bee'),false);assert.match(bot.reason,/Farmziel neu bewerten/);});


test('merchant clears scarce workspace before ordinary market and production acquisition',()=>{const {bot,c,cfg}=fixture();bot.me.role='merchant';cfg.merchant.mluck=cfg.merchant.stand=false;bot.free=()=>3;c.items=[{name:'ringsj',level:0}];const r={name:'Bankregel',action:'bank',priority:-400};let stored=0;bot.bank={pending:false,store(){stored++;return true;}};bot.exec.busy=()=>false;bot.logistics.travel=()=>{};bot.production={planGoals(){},status:()=>({}),tick:()=>assert.fail('Workspace must be freed first')};bot.economy={safe:()=>true,rules:()=>r,remaining:()=>true,spare:()=>1};bot.services={active:false};createMerchant(bot).tick();assert.equal(stored,1);});
