import {identity} from '../core/policy.mjs';
const identityVariant=(a,b)=>identity(a)===identity(b);
import {materialDrops} from './materials.mjs';
import {gearScore,gearCompatible,gearSuitability} from './gear.mjs';
import {defaultsFor} from '../../editor/lib/contract.mjs';
import {ITEM_RULE} from '../../editor/lib/schema.mjs';
const HISTORICAL_CHANCES={upgrade:[[.9999999,.98,.95,.7,.6,.4,.25,.15,.07,.024],[.99998,.97,.94,.68,.58,.38,.24,.14,.066,.018],[.97,.94,.92,.64,.52,.32,.232,.13,.062,.015]],compound:[[.99,.75,.4,.25,.2,.1,.07,.05,.05,.05],[.9,.7,.4,.2,.15,.08,.07,.05,.05,.03],[.8,.6,.32,.16,.1,.07,.03,.03,.03,.02]]};
export function progressionChance(G,name,level,kind){const m=G.items?.[name];const table=kind==='compound'?G.compound:G.upgrade;const grade=Array.isArray(m?.grades)?level>=m.grades[1]?2:level>=m.grades[0]?1:0:m?.igrade??0;const value=table?.[grade]?.[level+1]??table?.chances?.[grade]?.[level+1]??HISTORICAL_CHANCES[kind]?.[Math.min(2,grade)]?.[level];return Number.isFinite(value)&&value>0&&value<=1?value:null;}
export function createEconomicIntelligence(bot){const {p,cfg,me}=bot;let evaluated=[],at=0,allocation=[],chances=new Map(),props=new Map(),propsVersion=p.G.version,profitAt=0,profits=[],stockEpoch=-1,stocks=null;
 function mutationChance(name,level,kind){const observed=chances.get(name+':'+level+':'+kind);return observed&&Date.now()-observed.at<3600000?observed.value:progressionChance(p.G,name,level,kind);}
 function properties(i){if(propsVersion!==p.G.version){propsVersion=p.G.version;props.clear();}const key=identity(i);if(props.has(key))return props.get(key);const value=p.call('item_properties',i);if(props.size>=512)props.clear();props.set(key,value);return value;}
 function stockItems(){if(stocks&&Number.isInteger(bot.decisionEpoch)&&stockEpoch===bot.decisionEpoch)return stocks;const result=p.c.items.filter(i=>i&&bot.economy.safe(i)).map(i=>({item:i,owner:me.name}));for(const [pack,items] of bot.bank?.packs?.()??[])for(const i of items)if(i&&bot.economy.safe(i))result.push({item:i,owner:me.name,pack});for(const [name,h] of bot.transport.peers)if(h.running&&h.realm===p.realm())for(const row of h.stock??[])result.push({item:row,owner:name});stocks=result.slice(0,400);stockEpoch=bot.decisionEpoch;return stocks;} function targets(){if(cfg.production.optimizeGear===false||!cfg.production.autoGear||!cfg.production.gear||cfg.general.testLogging===undefined)return [];if(Date.now()-at<cfg.general.planningTickMs)return evaluated;at=Date.now();evaluated=[];allocation=[];const ownedStock=stockItems();
  for(const member of cfg.characters.filter(c=>c.enabled)){const profile=member.name===me.name?bot.gear.snapshot():bot.gear.profile(member.name);if(!profile)continue;const role=member.gearRole==='auto'?profile.class==='priest'?'healer':profile.class==='merchant'?'economy':'dps':member.gearRole;
   for(const [slot,old] of Object.entries(Object.fromEntries([...new Set([...Object.keys(profile.slots),'mainhand','offhand','helmet','chest','pants','shoes','gloves','amulet','belt','cape','ring1','ring2','earring1','earring2','orb'])].map(slot=>[slot,profile.slots[slot]??null])))){if(old?.l||old?.b||cfg.production.gearTargets.some(g=>g.enabled&&g.character===member.name&&g.slot===slot))continue;let previous=0;try{previous=old?gearScore(properties(old),role,profile.class):0;}catch{continue;}
    let best=null;for(const name of new Set([...cfg.production.autoGearItems,...ownedStock.map(r=>r.item.name)])){if(!gearCompatible(p.G,profile,{name,level:0},slot))continue;const meta=p.G.items[name];for(let level=0;level<=(meta.upgrade||meta.compound?cfg.production.autoGearMaxLevel:0);level++){if(old?.name===name&&old.level>=level)continue;const explicit=bot.economy.explicit({name,level:Math.max(0,level-1)},'production');if(level>0&&explicit&&(explicit.action==='keep'||explicit.targetLevel<level))continue;
     const owned=ownedStock.filter(r=>r.item.name===name&&(r.item.level??0)<=level).sort((a,b)=>(b.item.level??0)-(a.item.level??0))[0];let chance=1,cost=owned?0:meta.g??Infinity;for(let l=owned?.item.level??0;l<level;l++){const c=mutationChance(name,l,meta.compound?'compound':'upgrade');if(c===null){chance=0;break;}const grade=p.call('item_grade',{name,level:l}),scroll=(meta.compound?'cscroll':'scroll')+grade;cost=(cost*(meta.compound?3:1)+(p.G.items[scroll]?.g??Infinity))/c;chance*=c;}
     if(chance<cfg.production.minChance||cost>cfg.production.autoGearBudget||!Number.isFinite(cost))continue;let score;try{const nextStats=properties({name,level}),oldStats=old?properties(old):null;if(!gearSuitability(oldStats,nextStats,role,profile.class,member.merchantMobility).ok)continue;score=gearScore(nextStats,role,profile.class);}catch{continue;}const improvement=score-previous,utility=improvement*chance/(1+cost/Math.max(1,cfg.production.autoGearBudget));if(improvement<Math.abs(previous)*cfg.production.minImprovement||utility<=0)continue;if(!best||utility>best.utility)best={name:'Optimiertes Gear '+member.name+' '+slot,item:name,level,quantity:1,character:member.name,slot,enabled:true,budget:cfg.production.autoGearBudget,priority:member.catchUp?35:15,utility,chance,estimatedCost:cost,sourceOwner:owned?.owner??null,sourceLevel:owned?.item.level??0,variant:owned?{stat_type:owned.item.stat_type??'',p:owned.item.p??'',title:owned.item.title??''}:undefined};
    }}if(best){evaluated.push(best);allocation.push({character:member.name,slot,item:best.item,level:best.level,utility:best.utility,state:'reserved',recipientSession:bot.transport.fresh(member.name)?.session??null});}}
  }return evaluated;
 }
 function futureGear(i){return targets().some(g=>g.item===i.name&&g.level>=(i.level??0));}
 // Discounted, quantity-bounded bids supplement the NPC baseline only when a
 // verified buyer is currently reachable; a future upgrade gets a larger haircut.
 function resaleValue(item,quantity=1,future=true){
  const npc=bot.economy.value(item);const bid=bot.market?.bidValuation?.(item,quantity,npc,{future});
  return Number.isFinite(bid?.unitValue)&&bid.unitValue>=npc?bid.unitValue:npc;
 }
 function mutationEconomics(i){const m=p.G.items[i.name],kind=m?.compound?'compound':'upgrade',factor=kind==='compound'?3:1,current=resaleValue(i,1,false),max=cfg.production.autoGearMaxLevel;if(!Number.isFinite(current)||current>cfg.production.lossBudget)return {level:i.level??0,ev:current,action:'bank',reason:'auto-mutation-exposure'};let best={level:i.level??0,ev:current,action:'sell'},value=resaleValue({...i,level:max},1,true);if(!Number.isFinite(value))return best;
  for(let l=max-1;l>=(i.level??0);l--){const c=mutationChance(i.name,l,kind),grade=p.call('item_grade',{...i,level:l}),scrollCost=p.G.items[(kind==='compound'?'cscroll':'scroll')+grade]?.g,immediate=resaleValue({...i,level:l},1,l>(i.level??0));if(!(c>=cfg.production.minChance)||!Number.isFinite(scrollCost)||!Number.isFinite(immediate)){value=immediate;continue;}const ev=(c*value-scrollCost)/factor;if(ev>immediate*(1+cfg.production.minImprovement)&&scrollCost<=cfg.production.helperMaxPrice){value=ev;if(l===(i.level??0))best={level:l+1,ev,action:kind};}else value=immediate;}
  return best;
 }
 function disposition(i){if(cfg.production.autoDisposition!==true||!bot.economy.safe(i)||bot.production.reservedQuantity(i)>0)return null;const m=p.G.items[i.name];if(!m||m.cash||m.quest||m.event||['pot','elixir','scroll','uscroll','cscroll','offering','stand','tool','booster'].includes(m.type))return null;
  if(m.upgrade||m.compound){if(futureGear(i))return null;const value=bot.economy.value(i),choice=mutationEconomics(i),count=p.c.items.filter(x=>x&&identityVariant(x,i)).reduce((n,x)=>n+(x.q??1),0);let action=me.role==='farmer'?'send':choice.action;
   if(me.role==='merchant'&&['upgrade','compound'].includes(action)&&(!cfg.production.enabled||!cfg.production[action]))action='bank';if(action==='compound'&&count<3)action='bank';if(action==='sell'&&value>(cfg.production.autoSellMaxValue??100))action='bank';if(action==='bank'&&!cfg.merchant.bank)return null;
   return {...defaultsFor(ITEM_RULE),name:'Ökonomische Kurve '+i.name,item:i.name,minLevel:i.level??0,maxLevel:i.level??0,statType:i.stat_type??'',property:i.p??'',title:i.title??'',role:me.role,character:me.name,recipient:cfg.party.merchant,action,priority:-400,_autoDisposition:true,targetLevel:choice.level,targetCount:100,maxCount:100,batch:action==='compound'?3:1,minChance:cfg.production.minChance,goldBudget:cfg.production.helperMaxPrice,lossBudget:cfg.production.lossBudget,minPrice:Math.floor(value),keep:0};
  }
  const recipeUsed=Object.values(p.G.craft??{}).some(r=>(r.items??[]).some(x=>x[1]===i.name)),value=bot.economy.value(i);const rewards=Number.isSafeInteger(m.e)&&m.e>0?materialDrops(p.G,p.G.drops?.[i.name]):[],returnValue=rewards.reduce((n,r)=>n+r.chance*r.quantity*bot.economy.value({name:r.item,level:0}),0),valuableProbability=Math.min(1,rewards.filter(r=>bot.economy.value({name:r.item,level:0})>0).reduce((n,r)=>n+r.chance,0)),processable=cfg.production.enabled&&cfg.production.exchange&&bot.count(i.name)>=m.e&&valuableProbability>=cfg.production.minChance&&returnValue>value*m.e*(1+cfg.production.minImprovement)&&value*m.e<=cfg.production.lossBudget;const action=me.role==='farmer'?(cfg.party.merchant&&cfg.merchant.pickup?'send':null):processable?'exchange':recipeUsed?'bank':Number.isFinite(value)&&value<=(cfg.production.autoSellMaxValue??100)?'sell':'bank';if(!action||action==='bank'&&!cfg.merchant.bank)return null;
  return {...defaultsFor(ITEM_RULE),name:'Ökonomische Disposition '+i.name,item:i.name,role:me.role,character:me.name,recipient:action==='send'?cfg.party.merchant:'',action,priority:-500,_autoDisposition:true,minLevel:0,maxLevel:0,batch:100,maxCount:100000,targetCount:100000,lossBudget:cfg.production.lossBudget,minChance:cfg.production.minChance,minPrice:action==='sell'?Math.floor(value):1,keep:me.role==='merchant'&&recipeUsed?10:0};
 }
 function profitGoals(){if(Number.isInteger(bot.decisionEpoch)&&Date.now()-profitAt<1000)return profits;if(me.role!=='merchant'||!cfg.production.enabled||!cfg.production.autonomy||!cfg.production.autoDisposition)return [];const result=[],stock=stockItems();for(const {item:i} of stock){if(bot.economy.explicit(i)||futureGear(i)||!p.G.items[i.name]?.upgrade&&!p.G.items[i.name]?.compound)continue;const choice=mutationEconomics(i),kind=choice.action;if(!['upgrade','compound'].includes(kind)||!cfg.production[kind])continue;const sources=stock.filter(r=>identityVariant(r.item,i));if(kind==='compound'&&sources.reduce((n,r)=>n+(r.item.q??1),0)<3)continue;if(choice.ev<=bot.economy.value(i))continue;const goal={name:'Gewinnproduktion '+i.name+' +'+choice.level,enabled:true,item:i.name,level:choice.level,quantity:1,recipient:'',priority:-100,budget:Math.min(cfg.production.lossBudget,cfg.production.helperMaxPrice),variant:{stat_type:i.stat_type,p:i.p,title:i.title,data:i.data}};if(!result.some(g=>g.item===goal.item&&g.level===goal.level&&JSON.stringify(g.variant)===JSON.stringify(goal.variant)))result.push(goal);}profitAt=Date.now();profits=result.slice(0,16);return profits;}
 function rules(){const candidates=[...p.c.items.filter(Boolean)];if(me.role==='merchant')for(const [,h] of bot.transport.peers)if(h.running&&h.realm===p.realm())for(const row of h.items??[])if(row.to===me.name&&row.surplus>0)candidates.push(row.variant??{name:row.item,level:0});return [...new Map(candidates.filter(i=>!bot.economy.explicit(i)).map(i=>[identity(i),disposition(i)])).values()].filter(Boolean).slice(0,64);}
 return {targets,disposition,rules,profitGoals,futureGear,mutationEconomics,stockItems,chance:mutationChance,recordChance(name,level,kind,value){if(Number.isFinite(value)&&value>0&&value<=1){if(chances.size>128)chances.clear();chances.set(name+':'+level+':'+kind,{value,at:Date.now()});at=0;}},status:()=>({targets:evaluated,allocations:allocation}),invalidate(){at=0;profitAt=0;stockEpoch=-1;stocks=null;}};}
