import {distance} from '../core/policy.mjs';
import {knowledgeFingerprint} from '../world/knowledge.mjs';
export function createEncounter(bot){
 const key='albot:pull:'+bot.me.name;let profiles=bot.p.read(key)??{},active=null,phase='RECOVER',capacity=1,context='',lastSave=0;
 function members(){return bot.farmers.map(n=>n===bot.me.name?{name:n,running:bot.running,hp:bot.p.c.hp,max_hp:bot.p.c.max_hp,mp:bot.p.c.mp,max_mp:bot.p.c.max_mp,gear:bot.gear?.snapshot(),capabilities:bot.capabilities?.snapshot()}:bot.transport.fresh(n)).filter(h=>h?.running&&!h.rip);}
 function complete(failed){if(!active)return;const row=profiles[active.key]??{samples:0,seconds:0,xp:0,failures:0};row.samples++;row.seconds+=(Date.now()-active.at)/1000;row.xp+=Math.max(0,(bot.p.c.xp??0)-active.xp);row.failures+=failed?1:0;row.at=Date.now();profiles[active.key]=row;active=null;profiles=Object.fromEntries(Object.entries(profiles).sort((a,b)=>b[1].at-a[1].at).slice(0,96));if(Date.now()-lastSave>30000){lastSave=Date.now();bot.p.write(key,profiles);}}
 function tick(){const ms=members(),target=bot.teamPlan?.target(),mobs=bot.monsters().filter(m=>bot.teamNames.includes(m.target)),healthy=ms.length===bot.farmers.length&&ms.every(h=>h.hp/h.max_hp>=(bot.cfg.farming.pullHp??.8)&&h.mp/Math.max(1,h.max_mp)>=(bot.cfg.farming.pullMp??.5));
  context=knowledgeFingerprint([ms.map(h=>[h.name,h.gear?.slots,h.gear?.stats]),target,bot.p.G.monsters?.[target]]);
  const aoe=ms.flatMap(h=>h.capabilities?.aoe??[]),max=bot.cfg.party.aoe&&aoe.length?Math.min(bot.cfg.farming.maxAggro,bot.cfg.party.aoeMaxTargets,Math.max(...aoe.map(s=>s.capacity))):1;
  capacity=1;for(let size=1;size<=max;size++){const row=profiles[context+':'+size];if(row?.failures&&row.failures/row.samples>.1)break;const prev=profiles[context+':'+capacity],rate=row?.xp/Math.max(1,row?.seconds??0),previous=prev?.xp/Math.max(1,prev?.seconds??0);if(size===1||row?.samples>=3&&rate>previous*1.05)capacity=size;else if(size===capacity+1&&healthy&&(prev?.samples??0)>=3&&bot.cfg.farming.adaptivePull!==false){capacity=size;break;}}
  if(bot.recovering||ms.some(h=>h.hp/h.max_hp<(bot.cfg.farming.restBelow??.3)||h.mp/Math.max(1,h.max_mp)<.15)){phase=mobs.length?'ABORT':'RECOVER';if(active)complete(true);}else if(!mobs.length){if(active)complete(false);phase=healthy?'BUILD':'RECOVER';}else if(!healthy)phase='HOLD';else if(mobs.length<capacity)phase='BUILD';else phase=mobs.every(m=>m.hp<(bot.p.c.attack??1)*2)?'FINISH':'BURN';
  if(active&&mobs.length)active.key=context+':'+Math.max(Number(active.key.split(':').at(-1)),Math.min(max,mobs.length));if(mobs.length&&!active)active={key:context+':'+Math.max(1,Math.min(max,mobs.length)),at:Date.now(),xp:bot.p.c.xp??0};
 }
 function permit(m){if(m.target)return true;if(bot.me.name!==bot.leader&&bot.cfg.party.enabled)return false;return phase==='BUILD'&&bot.monsters().filter(x=>bot.teamNames.includes(x.target)).length<capacity&&(m.mtype&&m.mtype!==bot.teamPlan.target()||bot.teamPlan.wantsCombat());}
 function pull(){if(bot.me.name!==bot.leader||phase!=='BUILD'||capacity<2||!bot.capabilities?.available(bot.me.name,'agitate'))return false;const range=bot.p.G.skills.agitate?.range??320,near=bot.monsters().filter(m=>distance(bot.p.c,m)<=range);if(near.length<2||near.length>capacity||near.some(m=>m.mtype!==bot.teamPlan.target()||m.target&&!bot.teamNames.includes(m.target)||!bot.strategy.safeTarget(m.mtype,m)))return false;return bot.skills.use('agitate',null,.35,2000);}
 return {tick,permit,pull,status:()=>({phase,capacity,context,profiles:Object.keys(profiles).length}),close(){complete(phase==='ABORT');bot.p.write(key,profiles);}};
}
