import {knowledgeFingerprint} from '../world/knowledge.mjs';
export function createThreatLedger(bot){const entries=new Map();let realm=bot.p.realm();
 const signature=m=>knowledgeFingerprint([m.id,m.mtype,m.map,m.in,m.max_hp,bot.p.G.monsters[m.mtype]]);
 function sample(){if(realm!==bot.p.realm()){entries.clear();realm=bot.p.realm();}const now=Date.now();for(const m of bot.monsters()){const fp=signature(m),old=entries.get(m.id);const row=old?.fingerprint===fp?old:{fingerprint:fp,hits:{},lost:false};row.at=now;row.monster=m.mtype;row.target=m.target??null;row.immune=!!m.immune||!!m.invincible;row.cc=Object.fromEntries(['stunned','entangled','frozen'].filter(k=>m.s?.[k]).map(k=>[k,m.s[k].ms??true]));entries.set(m.id,row);}for(const [id,x] of entries)if(now-x.at>10000)entries.delete(id);while(entries.size>128)entries.delete(entries.keys().next().value);}
 function hit(d){if(!bot.running||!(d?.damage>0))return;const m=bot.entity(d.target);if(m?.type!=='monster')return;sample();const x=entries.get(d.target);if(!x)return;x.hits[d.actor]=Date.now();x.hits=Object.fromEntries(Object.entries(x.hits).filter(([,at])=>Date.now()-at<10000).slice(-16));}
 function inspect(m){const x=entries.get(m.id);if(!x||x.fingerprint!==signature(m)||Date.now()-x.at>2000)return null;const actors=Object.keys(x.hits);return {...x,ownership:m.target&&!bot.teamNames.includes(m.target)?'foreign':actors.some(n=>bot.teamNames.includes(n))&&actors.some(n=>!bot.teamNames.includes(n))?'contested':actors.some(n=>bot.teamNames.includes(n))?'team-observed':'unclaimed'};}
 function death(d){const x=entries.get(d?.id),actor=d?.actor??d?.hid??d?.killer;if(x&&Object.keys(x.hits).some(n=>bot.teamNames.includes(n))&&actor&&!bot.teamNames.includes(actor)){bot.teamPlan?.lostKill(x.monster);bot.event('combat.contestedKill',{monster:x.monster,reason:'Fremder bestätigter Killing Blow nach Teamtreffer'});}entries.delete(d?.id);}
 return {sample,hit,death,inspect,permitted(m){const x=inspect(m);return !x?.immune&&(!bot.cfg.farming.avoidOthers||!['foreign','contested'].includes(x?.ownership));},status:()=>({entries:entries.size,contested:[...entries].filter(([,x])=>Object.keys(x.hits).some(n=>!bot.teamNames.includes(n))).length}),close(){entries.clear();}};
}
