import {materialEvent} from '../production/probability.mjs';
import {materialDrops,expectedMonsterGold} from '../production/materials.mjs';
import {distance,samePlace,xy} from '../core/policy.mjs';
import {spawnLocations,knowledgeFingerprint,mapGraph,mapHops} from './knowledge.mjs';
export function createTeamPlan(bot){
 const {p,cfg,me}=bot,key='albot:teamplan:'+me.name;let current=null,last=0,generation=0,history=p.read(key+':areas')??{},area=null,previous=Date.now(),lastXp=p.c.xp??0,lastGold=p.c.gold??0,absence=0,samples=0,lastSave=0,ranking=[],definition='',graph={edges:[]},roles={};
 if(!history||typeof history!=='object'||Array.isArray(history))history={};
 function candidates(){const explicit=me.farmTargets?.length?me.farmTargets:cfg.farming.targets;return cfg.farming.autoTargets===false||me.farmTargets?.length?explicit:Object.keys(p.G.monsters??{}).filter(id=>{const m=p.G.monsters[id];return !m.boss&&!(m.respawn<0)&&!m.cooperative&&!m.stationary;});}
 function allowed(id){return candidates().includes(id)&&materialEvent(p.G,id,p.root.S??p.parent.S).active&&bot.strategy.safeTarget(id,undefined,true,true);}
 function materialRequests(){return bot.transport.fresh(cfg.party.merchant)?.materials??[];}
 function valid(plan){if(!plan||plan.realm!==p.realm()||plan.expires<=Date.now()||plan.leader!==bot.leader||!['farm','material','elixir'].includes(plan.kind)||!Number.isFinite(plan.x)||!Number.isFinite(plan.y)||!bot.strategy.permittedMap(plan.map)||!allowed(plan.target))return false;
  const source=spawnLocations(p.G,[plan.target],cfg.world.excludedMaps,cfg.farming.pvp).find(s=>s.key===plan.key);if(!source||plan.definition!==source.definition||bot.content?.approve('farm:'+plan.map+':'+plan.target,[p.G.monsters[plan.target],p.G.maps[plan.map]?.monsters?.filter(s=>s.type===plan.target)])===false)return false;
  if(!plan.objective)return true;if(plan.kind==='elixir')return bot.elixirs?.objective()?.objective===plan.objective||bot.transport.fresh(plan.leader)?.elixir?.item===plan.item;
  return materialRequests().some(r=>r.objective===plan.objective&&(!r.expires||r.expires>Date.now())&&r.monster===plan.target);
 }
 function observe(){if(me.name!==bot.leader)return;const now=Date.now(),dt=Math.max(0,Math.min(5000,now-previous));previous=now;if(!current||!samePlace(p.c,current)||distance(p.c,current)>220){area=null;lastXp=p.c.xp??0;lastGold=p.c.gold??0;return;}
  const hour=new Date(now).getUTCHours(),id=p.realm()+':'+hour+':'+current.key,old=history[id]??{seconds:0,xp:0,gold:0,empty:0,foreign:0,deaths:0,lostKills:0,samples:0};const visible=bot.monsters().filter(m=>m.mtype===current.target&&distance(p.c,m)<500),foreign=Object.values(p.entities).filter(e=>e.type==='character'&&!bot.teamNames.includes(e.name)&&distance(p.c,e)<500).length;
  old.seconds+=dt/1000;old.xp+=Math.max(0,(p.c.xp??0)-lastXp);lastXp=p.c.xp??0;if(!bot.journal&&!bot.logistics.reserved&&!bot.gold?.reserved)old.gold=(old.gold??0)+Math.max(0,(p.c.gold??0)-lastGold);lastGold=p.c.gold??0;old.empty+=visible.length?0:dt/1000;old.foreign+=foreign*dt/1000;old.samples++;old.at=now;history[id]=old;area=id;absence=old.empty/Math.max(1,old.seconds);samples++;
  history=Object.fromEntries(Object.entries(history).sort((a,b)=>b[1].at-a[1].at).slice(0,96));if(now-lastSave>30000){lastSave=now;p.write(key+':areas',history);}
 }
 function capabilities(){const names=bot.farmers??[],members=names.map(name=>{const h=name===me.name?{name,running:bot.running,hp:p.c.hp,max_hp:p.c.max_hp,mp:p.c.mp,max_mp:p.c.max_mp,class:p.c.ctype,map:p.c.map,in:p.c.in,stats:{attack:p.c.attack,frequency:p.c.frequency},skills:p.G.skills?Object.entries(p.G.skills).filter(([,s])=>(!s.class||s.class.includes?.(p.c.ctype))&&(s.level??0)<=p.c.level).map(([id])=>id):[]}:bot.transport.fresh(name);return h?{...h,name}:null;}).filter(h=>h?.running&&!h.rip);
  const assign=(classes,skill)=>members.filter(h=>classes.includes(h.class)&&(!h.skills||h.skills.includes(skill))).sort((a,b)=>b.hp/Math.max(1,b.max_hp)-a.hp/Math.max(1,a.max_hp)||a.name.localeCompare(b.name))[0]?.name??null;
  roles={heal:assign(['priest'],'heal'),aggro:assign(['warrior','paladin'],'taunt'),protect:assign(['paladin','mage'],'reflection'),energize:assign(['mage'],'energize'),speed:assign(['rogue'],'rspeed')};return roles;
 }
 function tick(){if(cfg.general.testLogging===undefined||me.role!=='farmer')return;observe();if(cfg.party.enabled&&me.name!==bot.leader){const h=bot.transport.fresh(bot.leader);const next=h?.running&&!h.rip? h?.farmPlan:null;if(valid(next)&&(!current||current.id!==next.id)){current={...next};roles=h.roles??{};if(['farm','world','combat','follow'].includes(bot.movement.order?.owner))bot.movement.stop();bot.target=null;bot.event('plan.adopt',{id:current.id,target:current.target,leader:bot.leader,reason:current.reason});}else if(!valid(next))current=null;return;}
  if(Date.now()-last<Math.min(10000,cfg.world.cacheTtlMs)&&valid(current))return;last=Date.now();capabilities();const raw=knowledgeFingerprint([p.G.monsters,p.G.maps]);if(raw!==definition){definition=raw;graph=mapGraph(p.G);if(current&&!valid(current)){bot.event('plan.drift',{id:current.id,reason:'Spawn-/Monsterdefinition geändert'});current=null;}}
  const materials=materialRequests(),requests=materials.filter(r=>r.quantity>0&&(!r.expires||r.expires>Date.now())&&allowed(r.monster)&&(!r.sourceFingerprint||r.sourceFingerprint===knowledgeFingerprint([p.G.monsters[r.monster],p.G.drops?.monsters?.[r.monster]])));const elixir=bot.elixirs?.objective();const request=requests[0]??elixir;
  const types=request?[request.monster]:candidates().filter(allowed),locations=spawnLocations(p.G,types,cfg.world.excludedMaps,cfg.farming.pvp),teamDps=Math.max(1,bot.farmers.reduce((n,name)=>{const h=name===me.name?p.c:bot.transport.fresh(name);return n+(h&&!h.rip&&(name===me.name||h.running)?(h.attack??h.stats?.attack??0)*(h.frequency??h.stats?.frequency??1):0);},0));
  const aoe=cfg.party.aoe?Math.min(cfg.party.aoeMaxTargets,bot.farmers.filter(n=>{const h=n===me.name?{class:p.c.ctype}:bot.transport.fresh(n);return ['ranger','warrior','rogue'].includes(h?.class);}).length+1):1;
  ranking=locations.filter(s=>bot.content?.approve('farm:'+s.map+':'+s.target,[p.G.monsters[s.target],p.G.maps[s.map]?.monsters?.filter(x=>x.type===s.target)])!==false).map(s=>{const m=p.G.monsters[s.target],seconds=Math.max(1,m.hp/teamDps),learned=history[p.realm()+':'+new Date().getUTCHours()+':'+s.key],hops=mapHops(graph,p.c.map,s.map),trip=s.map===p.c.map?distance(p.c,s)/Math.max(1,p.c.speed??40):Number.isFinite(hops)?hops*60:120;const density=Math.min(s.count,aoe,cfg.farming.maxAggro),empty=learned?.seconds>=30?learned.empty/learned.seconds:0,foreign=learned?.seconds>=30?learned.foreign/learned.seconds:0;
   const killsPerHour=Math.min(3600/seconds*density,s.count*3600/(seconds+Math.max(0,m.respawn??0))),theoretical=(m.xp??0)*killsPerHour,empirical=learned?.seconds>=60?learned.xp*3600/learned.seconds:theoretical,xp=theoretical*.7+empirical*.3,gold=expectedMonsterGold(p.G,s.target)*killsPerHour*.7+(learned?.seconds>=60?(learned.gold??0)*3600/learned.seconds:expectedMonsterGold(p.G,s.target)*killsPerHour)*.3;const utility=request?1/Math.max(.01,request.estimatedHours??request.p90Hours??1):cfg.farming.mode==='xp'?xp:cfg.farming.mode==='gold'?gold:Math.sqrt(Math.max(1,xp)*Math.max(1,gold));return {...s,score:utility/(1+trip/300+empty*2+foreign*.2+(learned?.deaths??0)+(learned?.lostKills??0)*.05),xpPerHour:xp,goldPerHour:gold,travelSeconds:trip,pressure:empty>.6?'spawn-starved':foreign>2?'contested':'healthy'};}).filter(r=>Number.isFinite(r.score)).sort((a,b)=>b.score-a.score||a.key.localeCompare(b.key));
  let next=ranking[0];const old=ranking.find(r=>r.key===current?.key);if(old&&valid(current)&&!request&&Date.now()-current.started<(cfg.farming.planHoldMs??60000)||old&&valid(current)&&!request&&next&&next.score<old.score*(1+(cfg.farming.switchImprovement??.2)))next=old;
  if(!next){current=null;return;}const same=current?.key===next.key&&current.objective===(request?.objective??null);const bounds=next.bounds;const proposal={...next,bounds,definition:knowledgeFingerprint([p.G.monsters[next.target],bounds]),kind:request?(request.elixir?'elixir':'material'):'farm',objective:request?.objective??null,item:request?.item??null,leader:bot.leader,realm:p.realm(),id:same?current.id:bot.session+':plan:'+(++generation),started:same?current.started:Date.now(),expires:Date.now()+cfg.general.messageTtlMs*2,reason:request?'Gemeinsamer Material-/Elixierbedarf':'Sicherer Standort nach EXP/Gold, Reisezeit, Spawnangebot und Gruppeneignung'};
  if(!same){bot.target=null;if(['farm','world','combat'].includes(bot.movement.order?.owner))bot.movement.stop();bot.event('plan.selected',{id:proposal.id,target:proposal.target,map:proposal.map,objective:proposal.objective,reason:proposal.reason,score:proposal.score});}current=proposal;
 }
 return {tick,allowed,candidates,valid,roles:()=>roles,heartbeat:()=>current?{...current}:null,target:()=>valid(current)?current.target:null,travel(){if(!valid(current)||bot.strategy.busy)return false;if(me.name===bot.leader&&cfg.party.enabled&&cfg.party.waitForTeam&&bot.farmers.some(n=>n!==me.name&&(!bot.transport.fresh(n)?.running||bot.transport.fresh(n)?.rip||bot.transport.fresh(n)?.realm!==p.realm()))){bot.reason='Warte auf aktive Gruppe vor Farmreise';return true;}if(samePlace(p.c,current)&&distance(p.c,current)<=250)return false;bot.reason='Gemeinsamer Plan: '+current.target;bot.movement.go({...current,radius:100},'farm');return true;},materialActive:()=>!!current?.objective,wantsCombat:()=>!current?.objective||!(materialRequests().find(r=>r.objective===current.objective)?.remaining===0),lostKill(monster){if(current?.target===monster&&area&&history[area])history[area].lostKills=(history[area].lostKills??0)+1;},failed(reason){if(area&&history[area])history[area].deaths++;if(current)bot.event('plan.failed',{id:current.id,reason});current=null;last=0;},status:()=>({current:current?{...current}:null,roles,areas:Object.keys(history).length,pressure:absence,ranking:ranking.slice(0,5),mapEdges:graph.edges.length}),close(){current=null;last=0;}};
}
